/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTrashRouteImport } from './routes/admin/trash'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPresignsRouteImport } from './routes/admin/presigns'
import { Route as AdminPoliciesRouteImport } from './routes/admin/policies'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminBucketsIndexRouteImport } from './routes/admin/buckets/index'
import { Route as AdminBucketsBucketRouteImport } from './routes/admin/buckets/$bucket'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrashRoute = AdminTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPresignsRoute = AdminPresignsRouteImport.update({
  id: '/presigns',
  path: '/presigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoliciesRoute = AdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBucketsIndexRoute = AdminBucketsIndexRouteImport.update({
  id: '/buckets/',
  path: '/buckets/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBucketsBucketRoute = AdminBucketsBucketRouteImport.update({
  id: '/buckets/$bucket',
  path: '/buckets/$bucket',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/presigns': typeof AdminPresignsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trash': typeof AdminTrashRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/buckets/$bucket': typeof AdminBucketsBucketRoute
  '/admin/buckets/': typeof AdminBucketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/presigns': typeof AdminPresignsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trash': typeof AdminTrashRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/buckets/$bucket': typeof AdminBucketsBucketRoute
  '/admin/buckets': typeof AdminBucketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/presigns': typeof AdminPresignsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trash': typeof AdminTrashRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/buckets/$bucket': typeof AdminBucketsBucketRoute
  '/admin/buckets/': typeof AdminBucketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/health'
    | '/login'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/policies'
    | '/admin/presigns'
    | '/admin/settings'
    | '/admin/trash'
    | '/admin/users'
    | '/api/$'
    | '/admin/buckets/$bucket'
    | '/admin/buckets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/health'
    | '/login'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/policies'
    | '/admin/presigns'
    | '/admin/settings'
    | '/admin/trash'
    | '/admin/users'
    | '/api/$'
    | '/admin/buckets/$bucket'
    | '/admin/buckets'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/health'
    | '/login'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/policies'
    | '/admin/presigns'
    | '/admin/settings'
    | '/admin/trash'
    | '/admin/users'
    | '/api/$'
    | '/admin/buckets/$bucket'
    | '/admin/buckets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trash': {
      id: '/admin/trash'
      path: '/trash'
      fullPath: '/admin/trash'
      preLoaderRoute: typeof AdminTrashRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/presigns': {
      id: '/admin/presigns'
      path: '/presigns'
      fullPath: '/admin/presigns'
      preLoaderRoute: typeof AdminPresignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policies': {
      id: '/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminPoliciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buckets/': {
      id: '/admin/buckets/'
      path: '/buckets'
      fullPath: '/admin/buckets/'
      preLoaderRoute: typeof AdminBucketsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buckets/$bucket': {
      id: '/admin/buckets/$bucket'
      path: '/buckets/$bucket'
      fullPath: '/admin/buckets/$bucket'
      preLoaderRoute: typeof AdminBucketsBucketRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPoliciesRoute: typeof AdminPoliciesRoute
  AdminPresignsRoute: typeof AdminPresignsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTrashRoute: typeof AdminTrashRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminBucketsBucketRoute: typeof AdminBucketsBucketRoute
  AdminBucketsIndexRoute: typeof AdminBucketsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPoliciesRoute: AdminPoliciesRoute,
  AdminPresignsRoute: AdminPresignsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTrashRoute: AdminTrashRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminBucketsBucketRoute: AdminBucketsBucketRoute,
  AdminBucketsIndexRoute: AdminBucketsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
